# Generated by Django 4.1 on 2022-09-03 20:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100, null=True),
        ),
    ]
