# Generated by Django 4.1 on 2022-09-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_detail_course_intro_alter_userdetail_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Staff', 'Staff'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
