# Generated by Django 4.1 on 2022-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_userdetail_course_userdetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], max_length=100, null=True),
        ),
    ]
